<a href="https://colab.research.google.com/github/YadavSanjay/elementary/blob/master/NumpyIndexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [16]:
a = np.array([ [[1,2,0],[3,4,5]], [[5,8,3],[7,6,1]],[[5,9,10],[9,12,11]] ])
print(a)
print(a.shape)

# print values corresponding to argmax o/p
# axis = 0
a0 = a.argmax(axis=0)
print(a0.shape)
a0_op = np.zeros(a0.shape, dtype=np.int32)
for i in range(a0.shape[0]):
  for j in range(a0.shape[1]):
    a0_op[i,j] = a[::,i:i+1:,j:j+1:].reshape(-1,)[a0[i][j]]
print(a0_op)

# axis = 1
a1 = a.argmax(axis=1)
print(a1.shape)
a1_op = np.zeros(a1.shape, dtype=np.int32)
for i in range(a1.shape[0]):
  for j in range(a1.shape[1]):
    a1_op[i,j] = a[i:i+1:,::,j:j+1:].reshape(-1,)[a1[i][j]]
print(a1_op)


# axis = 2
a2 = a.argmax(axis=2)
print(a2.shape)
a2_op = np.zeros(a2.shape, dtype=np.int32)
for i in range(a2.shape[0]):
  for j in range(a2.shape[1]):
    a2_op[i,j] = a[i:i+1:,j:j+1:,::].reshape(-1,)[a2[i][j]]
print(a2_op)


[[[ 1  2  0]
  [ 3  4  5]]

 [[ 5  8  3]
  [ 7  6  1]]

 [[ 5  9 10]
  [ 9 12 11]]]
(3, 2, 3)
(2, 3)
[[ 5  9 10]
 [ 9 12 11]]
(3, 3)
[[ 3  4  5]
 [ 7  8  3]
 [ 9 12 11]]
(3, 2)
[[ 2  5]
 [ 8  7]
 [10 12]]


In [9]:
print(a[::,0:1:,1:2:].reshape(-1,))
#[ [1,3,5,7,5,9], [2,4,8,6,9,12], [0,5,3,1,10,11] ]
#[ [1,3],[2,4],[0,5],[5,7],[8,6],[3,1],[5,9],[9,12],[10,11] ]

[2 8 9]
